### ISSUE TITLE
Not bot, only human

### ISSUE THREAD

**Issue by un-pogaz** [RolandR/place-atlas#26]
I'm sorry but the French flag on the bottom left is not build by bot, only human. If you continue to say that, you are of bad faith. The French were just well organized.

Here a mor accurate (and neutral) title
> French Streamer Flag
> 
> Flag created by a large number of largest French Streamers
> This flag is not assosiated to r/france

Here the Github of the french script [CorentinGC/reddit-place-kcorp](https://github.com/CorentinGC/reddit-place-kcorp), the term script is just a misnomer for a perfectly legitimate overlay.

Also, the Chazirad in this arena is the mascote of the Karmine Corp, french team LoL, created by Kameto one of the most active community on this arena. -> [Karmine Corp on Google](https://www.google.com/search?q=Karmine+Corp)

**Comment by tocram1** [comment]
Wow, I can't believe they flagged France as botters when there are proofs of cheating (using bots) from other parties AGAINST France (and no proofs of bots from France at all, that's just a false accusation).

**Comment by un-pogaz** [comment]
Shit, not the good Github, is the 2017
The 2022 is her https://github.com/Codixer/place-atlas
