### ISSUE TITLE
Change the canvas

### ISSUE THREAD

**Issue by Leguan16** [RolandR/place-atlas#44]
Hey,
I just want to ask if it would be possible to replace the current canvas with a cleaned and repaired one.

**Comment by AnonymousRandomPerson** [comment]
The point of the Atlas is to use the unmodified canvas.

**Comment by Leguan16** [comment]
I could swer it used a different version at the beginning. 

But i understand it. Just sad that some drawings, which have already been greifed before the picture has been taken, aren't fully displayed now.
