### ISSUE TITLE
Make it easier to suggest changes to existing entries

### ISSUE THREAD

**Issue by RolandR** [RolandR/place-atlas#5]
Implement a script-processable way of suggesting changes.

**Comment by Ajedi32** [comment]
If you automate the build process it might be possible to get a bot going to automatically submit PRs to this repo every time somebody suggests a change on the subreddit... just a thought.

**Comment by RolandR** [comment]
I have now implemented most of the edit requests (#b5bf8d3132ebb9391a4f8b22f549e8bd4a25f44d and #b61d1ae3af1fe0aacc0da967bfd6b8fe7c6f367e), so I'll pass on adding something for automating them unless there's a new flood of edit requests.

**Comment by Stevoisiak** [comment]
Is it possible to store the various entries in the code on GitHub so edits could be suggested as Pull Requests?

**Comment by Ajedi32** [comment]
They are stored in the code: https://github.com/RolandR/place-atlas/blob/master/web/_js/atlas.js

Only problem is they're stored in two places, and one of them is minified. That's why I was suggesting automating the build process.

Not sure there are really that many edits left to make at this point though.

**Comment by RolandR** [comment]
Yeah, atlas.js is is the file where all the entries are stored.

However, I'd prefer not to get entry edits as pull requests, because it's easier if all the edits and suggestions are in one place, which is [/r/placeAtlas](https://www.reddit.com/r/placeAtlas/).

It takes me one or two minutes to implement one edit request by hand, which is fast enough for me.
