### ISSUE TITLE
Limit pan and scroll zooming

### ISSUE THREAD

**Issue by wjdp** [RolandR/place-atlas#7]
On my trackpad it zooms far too far in and far too far out (screencast https://vid.me/4d7s).

Can we limit panning the atlas outside of the viewport, and limit zoom in and out to sensible levels?

**Comment by RolandR** [comment]
Zooming has been limited for a while now, and I've just limited panning in 5f35484eb5d8182627078c52cf2239cca31a0f5c.

I'd like to make it zoom less violently when using a trackpad, but I'll first need to get hands on a computer with one to test it.

Until then, double-clicking (ctrl for zooming out) works, and there are +- buttons for zooming as well.
