### ISSUE TITLE
"HAYIR" next to the flag of Turkey

### ISSUE THREAD

**Issue by ilhanyumer** [RolandR/place-atlas#8]
"HAYIR" means "NO" in Turkish. It is anti-Erdoğan. It is a refference to the https://en.wikipedia.org/wiki/Turkish_constitutional_referendum,_2017 which is going to take place in 16 April 2017.

**Comment by RolandR** [comment]
Somebody [added this](https://draemm.li/various/place-atlas/?id=1232).

In the future, please use the [subreddit](https://pay.reddit.com/r/placeAtlas/comments/63afic/how_to_contribute/) to suggest changes.
